### ISSUE TITLE
max rollout depth exceeded!  import copy rasied it ?

### ISSUE THREAD

**Issue by xhw98** [lightvector/leela-analysis#14]
when i want to use mtcs to play ,it rasied error :
  File "/home/mrmartinke/Desktop/MuGo-master/strategies.py", line 265, in estimate_value
    current = copy.deepcopy(leaf_position)
NameError: name 'copy' is not defined
so i import copy ,the game can run ,but it rasied this everytime :

**Move: 4. Captures X: 0 O: 0
max rollout depth exceeded!
value: 23.0
tree search**
thanks for your help!

**Comment by lightvector** [comment]
There is no such file as `strategies.py` in this repo. Perhaps you meant to ask your question in a different place?

**Comment by xhw98** [comment]
> There is no such file as `strategies.py` in this repo. Perhaps you meant to ask your question in a different place?

i feel so sorry for you,go to a wrong place!

**Comment by lightvector** [comment]
Okay I'm closing this issue now. Please ask your question to whoever actually wrote the program that you are trying to run.
