### ISSUE TITLE
One win rate inversion too many in graph_winrates()

### ISSUE THREAD

**Issue by hanspi42** [lightvector/leela-analysis#4]
The function graph_winrates() inverts win rates according to colour, but this has been done somewhere else before, so a winrate that should be constant becomes a triangle curve.

Fix: remove lines 25 and 26 of sfganalyze.py

    for move_num in sorted(winrates.keys()):
        pl, wr = winrates[move_num]
        # if pl != color:
        #    wr = 1. - wr
        X.append(move_num)
        Y.append(wr)

**Comment by lightvector** [comment]
Fixed, thanks!
