### ISSUE TITLE
Suggestion: Nicer, more informative graph

### ISSUE THREAD

**Issue by hanspi42** [lightvector/leela-analysis#7]
A suggestion: the graph is not well readable if there are lines, I think it is easier to identify when (at which move) something happens if the graph has no lines and a slightly different dimension.  Also, without reading Leela's doc, it is not clear whose win rate the script is showing.

Therefore, my suggestion for lines 30ff in the main script:

    plt.figure(1, figsize=(7,3.6))
    plt.axhline(0.5, 0, max(winrates.keys()), linestyle='--', color='0.7')
    plt.plot(X, Y, linestyle='None', color='k', marker='+')
    plt.xlim(0, max(winrates.keys()))
    plt.ylim(0, 1)
    plt.xlabel("Move number", fontsize=12)
    plt.ylabel("Black's win rate", fontsize=12)
    plt.savefig(outp_fn, dpi=200, format='pdf', bbox_inches='tight')

Thanks for maintaining this!  I use it on all my games and learn a lot.

**Comment by aTan-aka-Xellos** [comment]
@hanspi42 
Check impl of graph_winrates function in this fork:
https://github.com/jumpman24/sgf-analyzer/blob/master/sgftools/utils.py
It was tuned to have better graph

![025 03-jan-18 15 03](https://user-images.githubusercontent.com/7886823/34521602-3f14dace-f097-11e7-9021-516c190917e4.jpg)

**Comment by hanspi42** [comment]
This looks very good, but I would change two things:

- Write "Black's Win Rate" instead of only "Win Rate"

- also add vertical lines.

```python
    # fill graph with horizontal coordinate lines, step 0.25 ...
    for xc in np.arange(0, 1, 0.025):
        plt.axhline(xc, 0, max(winrates.keys()), linewidth=0.04, color='0.7')
    # ... and vertical coordinate lines, step 10:
    for xc in np.arange(0, max(winrates.keys()), 10):
	plt.axvline(xc, 0, 1, linewidth=0.04, color='0.7')
```

This makes it easier to locate a certain position where something happened in the sgf file:

[Pavia00-hanspi-20180104_analysis.pdf](https://github.com/lightvector/leela-analysis/files/1603758/Pavia00-hanspi-20180104_analysis.pdf)

Which analysis script is the one I should use and help improve, lightvector's or jumpman24's?

**Comment by aTan-aka-Xellos** [comment]
@hanspi42 
jumpman24's is a fork this one (lightvector's) with some significant changes. It's depends on you which would you prefer. Try both (play a bit with config.py values) and decide.

**Comment by lightvector** [comment]
@hanspi42 
Thanks for the suggestions! I pushed some changes to master to improve the graph, based mostly on the code you pasted here with some differences, take a look. If you have further suggestions, let me know and I will consider them, or feel free to submit a pull request. :)

**Comment by hanspi42** [comment]
I'll switch to pull requests, then. I hadn't worked with git enough yet to even know them :)
